### ISSUE TITLE
"target_link_directories" keyword not highlighted

### ISSUE THREAD

**Issue by caphosra** [twxs/vs.language.cmake#62]
![image](https://user-images.githubusercontent.com/28725713/78638263-efd8de80-78e6-11ea-9afb-066d9ba95bc9.png)

This is what I faced. The CMake keyword, "target_link_directories" aren't highlighted.
It wasn't fixed by recreating one.

Here is my environment status:
```
vscode: 1.43.2
twxs.cmake: latest
```

**Comment by caphosra** [comment]
Will it be fixed by #42 ?

**Comment by gudnimg** [comment]
This issue is still relevant. To add to this these three functions are missing highlighting:

* `target_link_directories()`
* `target_link_options()`
* `target_precompile_headers()`

![image](https://user-images.githubusercontent.com/8218499/105817000-eff8b680-5fac-11eb-8711-9e73a99ecd24.png)

```
vscode: 1.52.1
plugin version: 0.0.17
cmake: 3.19.3
```

**Comment by caphosra** [comment]
As far as I know, there are 4 issues (#41, #46, #71 and this one) which seem to be occurred due to the same reason.
